# RenameRelocate advanced configuration.
# Primary options (source folder, destination folder, suffix tag) are in
# Settings -> Plugins -> RenameRelocate.
# After changing this file: enable Dry Run, then Reload Plugins.
config = {
    "wrapper_styles": {
        "title": '',
        "performers": '()',
        "tag": '',
        "studio": '',
        "galleries": '',
        "resolution": '',
        "width": '',
        "height": '',
        "video_codec": '',
        "frame_rate": '',
        "date": '',
    },
    "postfix_styles": {
        "title": '',
        "performers": '',
        "tag": '',
        "studio": '',
        "galleries": '',
        "resolution": 'P',
        "width": 'W',
        "height": 'P',
        "width_height_seperator": 'x',
        "video_codec": '',
        "frame_rate": 'FR',
        "date": '',
    },
    "excludeTags": [
        "DuplicateMarkForDeletion",
        "DuplicateMarkForSwap",
        "DuplicateWhitelistFile",
        "_DuplicateMarkForDeletion",
        "_DuplicateMarkForSwap",
        "_DuplicateWhitelistFile",
        "ExcludeDuplicateMarkForDeletion",
        "_ExcludeDuplicateMarkForDeletion",
    ],
    "pathToExclude": "",
    "tagWhitelist": "",
    "if_notitle_use_org_filename": True,
    "max_filename_length": 255,
    "excludeIgnoreAutoTags": True,
    "performerAppendEnable": False,
    "studioAppendEnable": True,
    "tagAppendEnable": True,
    "fileRenameViaMove": True,
    "max_performers": -1,
    "rename_associated_files_enable": True,
    "associated_files_to_rename": [
        ".funscript", ".srt", ".vtt", ".scc", ".ttml", ".dfxp",
        ".lrc", ".cap", ".sami", ".stl", ".mcc", ".info", ".txt", ".xml",
    ],
    "handleExe": r"C:\\Sysinternals\\handle64.exe",
}
